# Generated by Django 5.0.1 on 2025-12-14 17:22

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserAccountSignup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Users_Profile_Picture', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image')),
                ('First_Name', models.CharField(max_length=25)),
                ('Last_Name', models.CharField(max_length=25)),
                ('Email', models.EmailField(max_length=254, unique=True)),
                ('Hashed_Password', models.CharField(max_length=128)),
                ('User_Is_Verified', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='UserOTPVerification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User_Email', models.EmailField(blank=True, max_length=254, null=True)),
                ('OTP', models.IntegerField(blank=True)),
            ],
        ),
    ]
