# Generated by Django 6.0 on 2025-12-13 06:18

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userverification', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccountsignup',
            name='Users_Profile_Picture',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
