# Generated by Django 6.0 on 2025-12-13 08:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userverification', '0002_useraccountsignup_users_profile_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccountsignup',
            name='OTP',
        ),
        migrations.AlterField(
            model_name='useraccountsignup',
            name='Confirm_Password',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='useraccountsignup',
            name='Password',
            field=models.CharField(max_length=128),
        ),
        migrations.CreateModel(
            name='UserAccountOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('OTP', models.IntegerField()),
                ('User_Email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userverification.useraccountsignup')),
            ],
        ),
    ]
