# Generated by Django 6.0 on 2025-12-13 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userverification', '0003_remove_useraccountsignup_otp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccountsignup',
            name='OTP',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='UserAccountOTP',
        ),
    ]
