# Generated by Django 6.0 on 2025-12-13 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userverification', '0004_useraccountsignup_otp_delete_useraccountotp'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccountsignup',
            name='User_Is_Verified',
            field=models.BooleanField(default=False),
        ),
    ]
