# Generated by Django 6.0 on 2025-12-13 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userverification', '0005_useraccountsignup_user_is_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccountsignup',
            name='Email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
