# Generated by Django 5.0.1 on 2025-12-14 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userverification', '0006_alter_useraccountsignup_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserOTPVerification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User_Email', models.EmailField(blank=True, max_length=254, null=True)),
                ('OTP', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='useraccountsignup',
            name='Confirm_Password',
        ),
        migrations.RemoveField(
            model_name='useraccountsignup',
            name='OTP',
        ),
        migrations.AlterField(
            model_name='useraccountsignup',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
