# Generated by Django 5.0.1 on 2025-12-14 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userverification', '0007_userotpverification_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userotpverification',
            name='OTP',
            field=models.IntegerField(blank=True),
        ),
    ]
