# Generated by Django 5.0.1 on 2025-12-15 13:12

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Category_Name', models.CharField(choices=[('CUPECO', 'Eco Cup Set'), ('ECOSPOONERY', 'Eco Spoon & Fork Set'), ('BAMBOOPLATE', 'Bamboo Plate Set'), ('WOODBOWL', 'Wooden Bowl Set'), ('LEAFPLATE', 'Leaf Plate Set'), ('COCONUTBOWL', 'Coconut Shell Bowl'), ('CLAYMUG', 'Clay Mug'), ('CLAYPLATE', 'Clay Plate'), ('WOODTRAY', 'Wooden Serving Tray'), ('BAMBOOSTRAW', 'Bamboo Straw Set'), ('STEELSTRAW', 'Steel Straw Set'), ('ECOWATERBOTTLE', 'Eco Water Bottle'), ('WOODCUTLERY', 'Wooden Cutlery Set'), ('BAMBOOCHOPSTICK', 'Bamboo Chopsticks'), ('KITCHENORGANIZER', 'Kitchen Organizer'), ('SPICEBOX', 'Wooden Spice Box'), ('LUNCHBOXECO', 'Eco Lunch Box'), ('TEASETCLAY', 'Clay Tea Set'), ('SERVINGSET', 'Eco Serving Set')], max_length=20)),
                ('Category_Picture', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
            ],
        ),
    ]
