# Generated by Django 5.0.1 on 2025-12-14 17:22

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product_Image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image')),
                ('Product_Name', models.CharField(max_length=40)),
                ('Product_Category', models.CharField(choices=[('COS', 'COSMETICS'), ('CLT', 'CLOTHES'), ('ELC', 'ELECTRONICS'), ('FOD', 'FOOD & GROCERY'), ('BKS', 'BOOKS'), ('HOM', 'HOME & LIVING'), ('SPT', 'SPORTS & FITNESS'), ('TOY', 'TOYS & GAMES'), ('HLC', 'HEALTH CARE'), ('JWL', 'JEWELRY'), ('SHO', 'SHOES & FOOTWEAR'), ('BAG', 'BAGS & ACCESSORIES'), ('WTC', 'WATCHES'), ('PET', 'PET SUPPLIES'), ('AUT', 'AUTOMOTIVE')], max_length=3)),
                ('Product_Description', models.TextField()),
                ('Product_Price', models.IntegerField(default=0.0)),
            ],
        ),
    ]
