# Generated by Django 6.0 on 2025-12-13 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product_Name', models.CharField(max_length=40)),
                ('Product_Category', models.CharField(choices=[('COS', 'COSMETICS'), ('CLT', 'CLOTHES'), ('ELC', 'ELECTRONICS'), ('FOD', 'FOOD & GROCERY'), ('BKS', 'BOOKS'), ('HOM', 'HOME & LIVING'), ('SPT', 'SPORTS & FITNESS'), ('TOY', 'TOYS & GAMES'), ('HLC', 'HEALTH CARE'), ('JWL', 'JEWELRY'), ('SHO', 'SHOES & FOOTWEAR'), ('BAG', 'BAGS & ACCESSORIES'), ('WTC', 'WATCHES'), ('PET', 'PET SUPPLIES'), ('AUT', 'AUTOMOTIVE')], max_length=3)),
                ('Product_Description', models.TextField()),
                ('Product_Price', models.IntegerField(default=0.0)),
            ],
        ),
    ]
