# Generated by Django 5.0.1 on 2025-12-14 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Users_Full_Name', models.CharField(max_length=50)),
                ('User_Profession', models.CharField(choices=[('ENG', 'Engineer'), ('DOC', 'Doctor'), ('I.T', 'Information Technologist'), ('LAW', 'Lawyer'), ('ARC', 'Architect'), ('ACC', 'Accountant'), ('BUS', 'Business Owner'), ('TEA', 'Teacher'), ('LEC', 'Lecturer'), ('DES', 'Designer'), ('DEV', 'Software Developer'), ('ANA', 'Data Analyst'), ('SCI', 'Scientist'), ('JOU', 'Journalist'), ('MKT', 'Marketing Specialist'), ('FIN', 'Financial Analyst'), ('HRM', 'Human Resource Manager'), ('ADM', 'Administrator'), ('CON', 'Consultant'), ('OTH', 'Other')], default='None', max_length=20)),
                ('User_Review', models.TextField(blank=True, default='None, as such!')),
            ],
        ),
    ]
